name: Deploy Docs to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn install --frozen-lockfile
        working-directory: website
      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - run: yarn run deploy
        working-directory: website


